---
- name: Register RHEL subscription
  community.general.redhat_subscription:
    activationkey: "{{ rh_activation_key }}"
    org_id: "{{ rh_org_id }}"
    state: present
  no_log: true

- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}.{{ domain }}"

- name: Update all packages  # noqa: package-latest
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Check whether a reboot is required
  ansible.builtin.command: dnf needs-restarting --reboothint
  register: base_config_needs_restarting
  changed_when: base_config_needs_restarting.rc == 1
  failed_when: base_config_needs_restarting.rc not in [0, 1]
  notify: Reboot after update
