---
all:
  children:
    hypervisors:
      hosts:
        localhost:
          ansible_connection: local
          ansible_python_interpreter: "{{ ansible_playbook_python }}"
          image_dir: /var/lib/libvirt/images
          bridge_bm: bm

    utility_vms:
      hosts:
        utility:
          ansible_host: 192.168.203.254
          ansible_user: root
          ansible_ssh_private_key_file: files/.ssh/id_rsa
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"

    ceph_vms:
      hosts:
        ceph:
          ansible_host: 192.168.203.252
          ansible_user: root
          ansible_ssh_private_key_file: files/.ssh/id_rsa
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null"
