---
- name: Enable IP forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: true
    state: present
    reload: true

- name: Configure NAT masquerade for baremetal network
  ansible.builtin.iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ baremetal_net.net }}/{{ baremetal_net.prefix }}"
    jump: MASQUERADE
    state: present
  when: hypervisor_enable_nat | bool
  notify: Save iptables

- name: Allow forwarding from baremetal network
  ansible.builtin.iptables:
    chain: FORWARD
    source: "{{ baremetal_net.net }}/{{ baremetal_net.prefix }}"
    jump: ACCEPT
    state: present
  when: hypervisor_enable_nat | bool
  notify: Save iptables

- name: Allow forwarding to baremetal network
  ansible.builtin.iptables:
    chain: FORWARD
    destination: "{{ baremetal_net.net }}/{{ baremetal_net.prefix }}"
    jump: ACCEPT
    state: present
  when: hypervisor_enable_nat | bool
  notify: Save iptables

- name: DNAT port 443 to ingress VIP
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ hypervisor_wan_interface }}"
    protocol: tcp
    destination_port: "443"
    jump: DNAT
    to_destination: "{{ vip.ingress }}:443"
    state: present
  when: hypervisor_enable_portfw | bool
  notify: Save iptables

- name: DNAT port 6443 to API VIP
  ansible.builtin.iptables:
    table: nat
    chain: PREROUTING
    in_interface: "{{ hypervisor_wan_interface }}"
    protocol: tcp
    destination_port: "6443"
    jump: DNAT
    to_destination: "{{ vip.api }}:6443"
    state: present
  when: hypervisor_enable_portfw | bool
  notify: Save iptables
