---
image_expand_partition: /dev/sda3

image_prepare_all_vms:
  - name: utility
    role: utility
    disk_gb: "{{ vm_specs.utility.os_disk_gb }}"
    ip: "{{ (cluster_nodes | selectattr('role', 'eq', 'utility') | first).ip }}"
  - name: ceph
    role: ceph
    disk_gb: "{{ vm_specs.ceph.os_disk_gb }}"
    ip: "{{ (cluster_nodes | selectattr('role', 'eq', 'ceph') | first).ip }}"

image_prepare_vms: >-
  {{ image_prepare_all_vms
     | selectattr('role', 'in',
         cluster_nodes
         | selectattr('hypervisor', 'eq', inventory_hostname)
         | map(attribute='role')
         | list)
     | list }}
