---
hypervisor_enable_nat: "{{ hypervisor.enable_nat | default(true) }}"
hypervisor_enable_portfw: "{{ hypervisor.enable_portfw | default(true) }}"
hypervisor_wan_interface: "{{ hypervisor.wan_interface | default('eth0') }}"
