---
- name: Configure DNS and DHCP on utility VM
  hosts: utility_vms
  become: true
  gather_facts: true
  roles:
    - role: base_config
      tags: [configure-utility]
    - role: dnsmasq
      tags: [configure-utility]
