---
- name: Wait for OpenShift cluster to be ready
  hosts: utility_vms
  become: true
  gather_facts: true
  tasks:
    - name: Monitor VMs and wait for API
      ansible.builtin.include_role:
        name: assisted_monitor
        tasks_from: monitor_vms

    - name: Monitor cluster readiness
      ansible.builtin.include_role:
        name: assisted_monitor
        tasks_from: wait_cluster
